### ISSUE TITLE
create document: basic.html

### ISSUE THREAD

**Issue by lcabrini** [henrypadi/henry-web-learning#1]
The file should reside in an html sub-directory of your main project folder.

**Comment by henrypadi** [comment]
I need a little help creating document 'basic.html'.

**Comment by henrypadi** [comment]
By the way, keyboard got fixed yesterday and running fine now. Thanks.

**Comment by lcabrini** [comment]
Don't worry, we'll go through how to create, commit and push the  file basic.html when we have our next session
